### ISSUE TITLE
TeslaSafe and RICE 2x Ads for 4 weeks

### ISSUE THREAD

**Issue by bobachef** [BogTools/Bogged-Token-List#176]
Hi @lukebogtools something strange happened with telegram and we were banned for no reason right after messaging you. Here is the information for the ads that we purchased. If you could reach out on discord my username is `Boba Chef#7795` thank you!

TeslaSafe Links
Twitter: https://www.twitter.com/fuzionchain
Telegram: https://t.me/fuzionchain
Discord: https://discord.gg/f8KvgsVtUE
Website: https://teslasafe.fi
Buy TeslaSafe on RiceFarm NOW: https://teslasafe.ricefarm.fi/

Rice Links
Twitter: https://www.twitter.com/fuzionchain
Telegram: https://t.me/fuzionchain
Discord: https://discord.gg/f8KvgsVtUE
Website: https://ricefarm.fi
Buy: https://exchange.pancakeswap.finance/#/swap?outputCurrency=0xC4eEFF5aab678C3FF32362D80946A3f5De4a1861

TeslaSafe 1:
🚀🚀🚀TeslaSafe has continued to outperform the top 100 crypto in the past 2 months because of its continued development. It’s ahead of schedule & hit every milestone on their roadmap. TeslaSafe will eventually burn 99% of it’s current circulating supply & is considered the most deflationary crypto asset in the world.⚡️⚡️⚡️

TeslaSafe 2:
🚀🚀🚀TeslaSafe had the fastest presale in history & is the 1st token of the FuZion Blockchain which will boast 1 million tps. In contrast, ETH can execute 14 tps and BSC can execute 58 tps. TeslaSafe is the first smart staking protocol that has expanded its use cases & is growing at a rapid rate.⚡️⚡️⚡️

Rice 1:
🚀🚀🚀 RICE will be the lead DEX/AMM token for the FuZion Blockchain which will support up to 1 million tps.  Rice has outperformed the market since its creation & is the most deflationary DEX/AMM token in the world. It’s burn rate is higher than UNI & Cake combined. It’s anti-whale policies keep buy pressure constant. Come check out our vaults!⚡️⚡️⚡️

Rice 2:
🚀🚀🚀 RICE is the most deflationary DEX crypto in the world, having a deflationary rate higher than both UNI & Cake. It has a lower max supply than both and has executed their DAPP faster than any other token of similar function. They’re one of the fastest growing DAPPs on BSC. RiceFarm will be the lead DEX on the FuZion Blockchain. Come check out our vaults!⚡️⚡️⚡️

**Comment by lukebogtools** [comment]
Thanks, sorry to hear you got banned. Ads will go live tomorrow -- just have to make a few code changes to accommodate custom links.

**Comment by bobachef** [comment]
awesome! we were able to get back in our accounts luckily within 24 hours.
