### ISSUE TITLE
#354 i have added everything and it was merged more than 19 days ago ! What is this?

### ISSUE THREAD

**Issue by PayFlow-Token** [BogTools/Bogged-Token-List#381]
Hello,

i have added everything correct and it was merged by Lukebogtools into Bogtools:main but i dont see any information?
i got the Embedded boggedswap and the chart in my Telegram bot.
And you keep merging other projects but dont look at my issue ? Why ? @lukebogtools 
What now?

**Comment by lukebogtools** [comment]
Whats your contract address, I'll look into it.

**Comment by PayFlow-Token** [comment]
https://bscscan.com/token/0xe3b42852a85d38b18076ab2dd96b0f894cc0636c

**Comment by PayFlow-Token** [comment]
You can look at the merged #354 you merged it more than 20 days ago @lukebogtools

**Comment by PayFlow-Token** [comment]
@lukebogtools
